-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

CREATE GLOBAL TEMPORARY TABLE DUENO_DIAS_SCOOTER_RECARGA(
  SERVICIO_ID   NUMBER(10,0)  NOT NULL,
  SCOOTER_ID    NUMBER(10,0)  NOT NULL,
  USUARIO_ID    NUMBER(10,0)  NOT NULL,
  EMAIL         VARCHAR2(40)  NOT NULL,
  NOMBRE        VARCHAR2(40)  NOT NULL,
  FECHA_INICIO  DATE          NOT NULL
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE GASTO_TOTAL_SERVICIOS(
  USUARIO_ID       NUMBER(10,0)  NOT NULL,
  TIPO_SERVICIO    CHAR(1)       NOT NULL,
  PRECIO_UNITARIO  NUMBER(7,2)  NOT NULL,
  CANTIDAD         NUMBER(10,0)  NOT NULL,
  TOTAL            NUMBER(10,2)  NOT NULL
) ON COMMIT DELETE ROWS;
-- No sé por qué no sale el generated always as PRECIO_UNITARIO*CANTIDAD

CREATE GLOBAL TEMPORARY TABLE BANCOS_A_DEPOSITAR(
  NOMBRE_BANCO varchar2(100),
  CANTIDAD_CUENTAS NUMBER(10)
) ON COMMIT PRESERVE ROWS;


CREATE GLOBAL TEMPORARY TABLE T_DETALLE_RECARGAS(
  MARCA_ID    NUMBER(10,0),
  SCOOTER_ID  NUMBER(10,0),
  NUM_DIAS    NUMBER(3,0)
) ON COMMIT PRESERVE ROWS;
