CREATE OR REPLACE DIRECTORY order_entry_dir AS '';

CREATE TABLE ZONA(
  ZONA_ID     NUMBER(10,0)    NOT NULL,
  NOMBRE      VARCHAR2(40)    NOT NULL,
  POLIGONO    VARCHAR2(2000)  NOT NULL,
  CONSTRAINT ZONA_PK PRIMARY KEY (ZONA_ID),
  CONSTRAINT ZONA_NOMBRE_UK UNIQUE(NOMBRE),
  CONSTRAINT ZONA_POLIGONO_UK UNIQUE(POLIGONO)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY USER_DIR1
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (emp_id,first_name,last_name,user_name)
  )
  LOCATION ('emp_xt_file1.txt')
)
PARALLEL
REJECT LIMIT UNLIMITED;

CREATE TABLE json_dump_file_contents (json_document BLOB)
  ORGANIZATION EXTERNAL
    (TYPE ORACLE_LOADER
     DEFAULT DIRECTORY order_entry_dir
     ACCESS PARAMETERS
       (RECORDS DELIMITED BY 0x'0A'
        FIELDS (json_document CHAR(5000)))
        LOCATION (order_entry_dir:'PurchaseOrders.dmp'))
  PARALLEL
  REJECT LIMIT UNLIMITED;