-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

CREATE INDEX HIST_SCOO_ST_STATUS_ID_IX ON HIST_SCOOTER_STATUS(STATUS_ID);

CREATE INDEX HIST_SCOO_ST_SCOOTER_ID_IX ON HIST_SCOOTER_STATUS(SCOOTER_ID);

CREATE INDEX IMG_REP_REPORTE_FALLA_ID_IX ON IMAGEN_REPORTE(REPORTE_FALLA_ID);

--CREATE UNIQUE INDEX IMG_REP_REPORTE_IMAGEN_UIX ON IMAGEN_REPORTE(DBMS_LOB.SUBSTR(IMAGEN));

CREATE INDEX REC_SCOO_SERVICIO_ID_IX ON RECARGA_SCOOTER(SERVICIO_ID);

CREATE INDEX REC_SCOO_SCOOTER_ID_IX ON RECARGA_SCOOTER(SCOOTER_ID);

CREATE UNIQUE INDEX REP_FALLA_USUARIO_SCOO_UIX ON REPORTE_FALLA(USUARIO_ID,SCOOTER_ID,LOWER(DESCRIPCION),FECHA_REPORTE);

CREATE UNIQUE INDEX SCOO_N_SERIE_MATRICULA_UIX ON SCOOTER(NUMERO_SERIE,MATRICULA);

CREATE UNIQUE INDEX SERVICIO_DUPLUCADO_UIX ON SERVICIO(USUARIO_ID,PRECIO,FECHA_INICIO,FECHA_FIN,TIPO_SERVICIO);

CREATE INDEX SCOO_MARCA_ID_IX ON SCOOTER(MARCA_ID);

CREATE INDEX SCOO_STATUS_ID_IX ON SCOOTER(STATUS_ID);

CREATE INDEX SCOO_SCOOTER_REEMP_ID_IX ON SCOOTER(SCOOTER_REEMPLAZO_ID);

CREATE INDEX SERVICIO_USUARIO_ID_IX ON SERVICIO(USUARIO_ID);

CREATE INDEX SERV_REC_SERVICIO_ID_IX ON SERVICIO_RECARGA(SERVICIO_ID,NOMBRE_BANCO);

CREATE INDEX SERV_REC_CLABE_INTER_UIX ON SERVICIO_RECARGA(CLABE_INTERBANCARIA);

CREATE INDEX SERV_RENTA_SCOOTER_ID_IX ON SERVICIO_RENTA(LOWER(DIRECCION),SCOOTER_ID);

CREATE INDEX SERV_VIAJE_SERVICIO_ID_IX ON SERVICIO_VIAJE(SERVICIO_ID,LOWER(FOLIO));

CREATE UNIQUE INDEX TARJ_CLIENTE_TARJETA_UIX ON TARJETA_CLIENTE(NUMERO_TARJETA,MES_EXPIRACION,ANIO_EXPIRACION);

CREATE INDEX TARJ_PREPAGO_USUARIO_ID_IX ON TARJETA_PREPAGO(USUARIO_ID);

CREATE INDEX TEL_MARCA_MARCA_ID_IX ON TELEFONO_MARCA(MARCA_ID);

CREATE UNIQUE INDEX UBICACION_SCOOTER_ID_IX ON UBICACION(SCOOTER_ID,LATITUD,LONGITUD,TO_CHAR(FECHA_HORA));
