-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

-- SINÓNIMOS PÚBLICOS
CREATE OR REPLACE PUBLIC SYNONYM XXMARCA FOR MARCA;
CREATE OR REPLACE PUBLIC SYNONYM UBICACION FOR UBICACION;
CREATE OR REPLACE PUBLIC SYNONYM ZONA FOR ZONA;

-- PERMISOS LECTURA
GRANT SELECT ON CG_PROY_ADMIN.USUARIO TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.STATUS TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.SCOOTER TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.ZONA_SCOOTER TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.REPORTE_FALLA TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.IMAGEN_REPORTE TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.SERVICIO TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.SERVICIO_VIAJE TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.SERVICIO_RENTA TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.SERVICIO_RECARGA TO CG_PROY_INVITADO;
GRANT SELECT ON CG_PROY_ADMIN.RECARGA_SCOOTER TO CG_PROY_INVITADO;


CONNECT CG_PROY_INVITADO/samjor
--CREACIÓN DE SINÓNIMOS

CREATE OR REPLACE SYNONYM USUARIO FOR CG_PROY_ADMIN.USUARIO;
CREATE OR REPLACE SYNONYM STATUS FOR CG_PROY_ADMIN.STATUS;
CREATE OR REPLACE SYNONYM SCOOTER FOR CG_PROY_ADMIN.SCOOTER;
CREATE OR REPLACE SYNONYM ZONA_SCOOTER FOR CG_PROY_ADMIN.ZONA_SCOOTER;
CREATE OR REPLACE SYNONYM REPORTE_FALLA FOR CG_PROY_ADMIN.REPORTE_FALLA;
CREATE OR REPLACE SYNONYM IMAGEN_REPORTE FOR CG_PROY_ADMIN.IMAGEN_REPORTE;
CREATE OR REPLACE SYNONYM SERVICIO FOR CG_PROY_ADMIN.SERVICIO;
CREATE OR REPLACE SYNONYM SERVICIO_VIAJE FOR CG_PROY_ADMIN.SERVICIO_VIAJE;
CREATE OR REPLACE SYNONYM SERVICIO_RENTA FOR CG_PROY_ADMIN.SERVICIO_RENTA;
CREATE OR REPLACE SYNONYM SERVICIO_RECARGA FOR CG_PROY_ADMIN.SERVICIO_RECARGA;
CREATE OR REPLACE SYNONYM RECARGA_SCOOTER FOR CG_PROY_ADMIN.RECARGA_SCOOTER;

-- MENOS TARJETA, TARJETAS PREPAGO, HISTÓRICO DE STATUS Y TELÉFONOS MARCAS
CONNECT CG_PROY_ADMIN/samjor

-- CREACIÓN DE SINÓNIMOS PRIVADOS DEL PROGRAMA XX
    
DECLARE
  STR VARCHAR2(100);
BEGIN
  for R in (select * from USER_TABLES) loop
    STR := 'CREATE OR REPLACE SYNONYM XX_'|| R.table_name ||' FOR '|| R.table_name ||';';
    DBMS_OUTPUT.PUT_LINE(STR);
  end loop;
END;
/

-- NO TENGO NI LA MÁS IDEA DE POR QUÉ NO JALA EL EXECUTE IMMEDIATE ARRIBA 
CREATE OR REPLACE SYNONYM XX_ZONA_EXERNA FOR ZONA_EXERNA;
CREATE OR REPLACE SYNONYM XX_ZONA FOR ZONA;
CREATE OR REPLACE SYNONYM XX_RECARGA_SCOOTER FOR RECARGA_SCOOTER;
CREATE OR REPLACE SYNONYM XX_SERVICIO_RECARGA FOR SERVICIO_RECARGA;
CREATE OR REPLACE SYNONYM XX_SERVICIO_RENTA FOR SERVICIO_RENTA;
CREATE OR REPLACE SYNONYM XX_SERVICIO_VIAJE FOR SERVICIO_VIAJE;
CREATE OR REPLACE SYNONYM XX_SERVICIO FOR SERVICIO;
CREATE OR REPLACE SYNONYM XX_IMAGEN_REPORTE FOR IMAGEN_REPORTE;
CREATE OR REPLACE SYNONYM XX_REPORTE_FALLA FOR REPORTE_FALLA;
CREATE OR REPLACE SYNONYM XX_HIST_SCOOTER_STATUS FOR HIST_SCOOTER_STATUS;
CREATE OR REPLACE SYNONYM XX_ZONA_SCOOTER FOR ZONA_SCOOTER;
CREATE OR REPLACE SYNONYM XX_UBICACION FOR UBICACION;
CREATE OR REPLACE SYNONYM XX_SCOOTER FOR SCOOTER;
CREATE OR REPLACE SYNONYM XX_STATUS FOR STATUS;
CREATE OR REPLACE SYNONYM XX_TELEFONO_MARCA FOR TELEFONO_MARCA;
CREATE OR REPLACE SYNONYM XX_MARCA FOR MARCA;
CREATE OR REPLACE SYNONYM XX_TARJETA_CLIENTE FOR TARJETA_CLIENTE;
CREATE OR REPLACE SYNONYM XX_TARJETA_PREPAGO FOR TARJETA_PREPAGO;
CREATE OR REPLACE SYNONYM XX_USUARIO FOR USUARIO;