-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

CREATE OR REPLACE VIEW FORMAS_PAGO_DATOS_CLIENTES AS
SELECT U.USUARIO_ID AS USUARIO, U.EMAIL AS EMAIL,U.NOMBRE AS NOMBRE,
U.AP_PATERNO AS APELLIDO_PATERNO,
(SELECT SUM(IMPORTE) 
FROM TARJETA_PREPAGO TP 
WHERE TP.USUARIO_ID = U.USUARIO_ID
AND FECHA_EXPIRACION < SYSDATE
GROUP BY TP.USUARIO_ID
) AS CREDITOS, TC.NUMERO_TARJETA AS TARJETA_CREDITO
FROM USUARIO U,TARJETA_CLIENTE TC
WITH READ ONLY;

CREATE OR REPLACE VIEW TARJETAS_PREPAGO_NO_USADAS AS 
SELECT TARJETA_PREPAGO_ID,CODIGO_BARRAS,IMPORTE
FROM TARJETA_PREPAGO
WHERE USUARIO_ID IS NULL
WITH READ ONLY;

CREATE OR REPLACE VIEW TARJETA_CLIENTE_PARA_INVITADO AS 
SELECT NUMERO_TARJETA,(SELECT 'XX' AS MES FROM DUAL) AS MES,ANIO_EXPIRACION AS ANIO
FROM TARJETA_CLIENTE
WHERE USUARIO_ID IS NULL
WITH READ ONLY;

CREATE OR REPLACE VIEW REP_FALLA_MES_POR_USUARIO AS
SELECT USUARIO_ID AS USUARIO,COUNT(*) NUMERO
FROM REPORTE_FALLA 
WHERE EXTRACT(month FROM FECHA_REPORTE) = EXTRACT(month FROM SYSDATE)
GROUP BY USUARIO_ID
ORDER BY USUARIO_ID
WITH READ ONLY;

/*
CREATE OR REPLACE VIEW DEPOSITO AS
SELECT S.USUARIO_ID, SR.NOMBRE_BANCO, 
SR.CLABE_INTERBANCARIA,(RS.NIVEL_CARGA*0.2) AS PAGO,
(SELECT COUNT(*) FROM RECARGA_SCOOTER WHERE SERVICIO_ID = SR.SERVICIO_ID) AS CANTIDAD
FROM SERVICIO_RECARGA SR, RECARGA_SCOOTER RS, SERVICIO S
WHERE SR.SERVICIO_ID = S.SERVICIO_ID
AND 
WITH READ ONLY;
-- ¿CÓMO SABER CUÁNDO YA SE FINALIZÓ EL SERVICIO, PONER FECHA INICIO Y FIN
*/