-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

set feedback off
whenever sqlerror exit rollback

PROMPT INSERTANDO MARCAS

@s-09-carga-inicial-marcas.sql

PROMPT INSERTANDO STATUS

INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'AP','APAGADO');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'EE','EN ESPERA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'SV','EN SERVICIO VIAJE');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'BB','BATERIA BAJA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'CF','CON FALLAS');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'SR','EN SERVICIO RENTA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'SC','CON EN SERVICIO CARGA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'FZ','FUERA DE ZONA');

PROMPT INSERTANDO USUARIOS

@s-09-carga-inicial-usuario.sql

PROMPT INSERTANDO TARJETAS PREPAGO

@s-09-carga-inicial-tarjetaprepago.sql

PROMPT INSERTANDO TARJETAS DE CLIENTES

@s-09-carga-inicial-tarjeta-cliente.sql

PROMPT INSERTANDO LOS TELÉFONOS DE LAS MARCAS

@s-09-carga-inicial-telefono-marca.sql

PROMPT INSERTANDO SCOOTERS

@s-09-carga-inicial-scooters.sql

PROMPT INSERTANDO UBICACION DE SCOOTERS

@s-09-carga-inicial-ubicaciones1.sql
PROMPT CARGA 1 LISTA
@s-09-carga-inicial-ubicaciones2.sql
PROMPT CARGA 2 LISTA
@s-09-carga-inicial-ubicaciones3.sql
PROMPT CARGA 3 LISTA
@s-09-carga-inicial-ubicaciones4.sql
PROMPT CARGA 4 LISTA
@s-09-carga-inicial-ubicaciones5.sql
PROMPT CARGA 5 LISTA

PROMPT INSERTANDO UBICACION DE SCOOTERS

PROMPT LISTO! :)

set feedback on

