INSERT INTO STATUS_SERVICIO VALUES (SEQ_STATUS_SERVICIO.NEXTVAL,'INICIADO');
INSERT INTO STATUS_SERVICIO VALUES (SEQ_STATUS_SERVICIO.NEXTVAL,'EN CURSO');
INSERT INTO STATUS_SERVICIO VALUES (SEQ_STATUS_SERVICIO.NEXTVAL,'CANCELADO');
INSERT INTO STATUS_SERVICIO VALUES (SEQ_STATUS_SERVICIO.NEXTVAL,'TERMINADO');
INSERT INTO STATUS_SERVICIO VALUES (SEQ_STATUS_SERVICIO.NEXTVAL,'MODIFICADO');

