INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'AP','APAGADO');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'EE','EN ESPERA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'SV','EN SERVICIO VIAJE');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'BB','BATERIA BAJA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'CF','CON FALLAS');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'SR','EN SERVICIO RENTA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'SC','EN SERVICIO CARGA');
INSERT INTO STATUS VALUES (SEQ_STATUS.NEXTVAL,'FZ','FUERA DE ZONA');