-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

/*  
    Primer trigger: Checar la fecha de insersión sea con respecto al caso de estudio.
    Segundo trigger: INICIAR SERVICIO. -> CAMBIAR STATUS DEL SCOOTER, QUITAR MONEY O CRÉDITO.
    TERCER TRIGGER: VERIFICAR QUE LA TARJETA DE CRÉDITO TENGA FONDOS
    CUARTO: ASIGNAR FUERA DE ZONA AL INSERTAR COORDENADAS
    QUINTO: VERIFICAR QUE EL SCOOTER NO SE ENCUENTRA EN OTRO SERVICIO EN CURSO.
*/

SET LINESIZE 200

PROMPT TRIGGER 1: SE DESEA QUE CADA VEZ QUE SE INICIE UN SERVICIO SE COBRE INSTANTÁNEAMENTE
PROMPT EL MONTO DEL PRECIO A LOS PUNTOS DEL USUARIO. SI ESTE NO DISPONE DE PUNTOS
PROMPT IREMOS A SU TARJETA DE CRÉDITO A VERIFICAR QUE SE ENCUENTRE VIGENTE. EN CASO CONTRARIO
PROMPT MARCAREMOS ERROR -20001. ADEMÁS VERIFICAMOS QUE LOS DIAS_CUSTODIA EN SERVICIO_RENTA ESTÁN CORRECTOS

CREATE OR REPLACE TRIGGER COBRAR
BEFORE INSERT OR UPDATE ON SERVICIO
FOR EACH ROW
DECLARE
  V_PUNTOS NUMBER:=0;
  V_MES_EXPIRA NUMBER:=0;
  V_ANIO_EXPIRA NUMBER:=0;
  V_DIAS_CUSTODIA NUMBER:=0;
  V_EXCENTO SERVICIO_VIAJE.SERVICIO_ID%TYPE;
BEGIN
SELECT PUNTOS INTO V_PUNTOS FROM USUARIO WHERE USUARIO_ID = :NEW.USUARIO_ID;
IF V_PUNTOS > :NEW.PRECIO THEN
    UPDATE USUARIO SET PUNTOS = PUNTOS - :NEW.PRECIO WHERE USUARIO_ID = :NEW.USUARIO_ID;
ELSE
  SELECT MES_EXPIRACION INTO V_MES_EXPIRA FROM TARJETA_CLIENTE WHERE USUARIO_ID = :NEW.USUARIO_ID;
  SELECT ANIO_EXPIRACION INTO V_ANIO_EXPIRA FROM TARJETA_CLIENTE WHERE USUARIO_ID = :NEW.USUARIO_ID;

  IF EXTRACT(YEAR FROM SYSDATE) > V_ANIO_EXPIRA THEN
    RAISE_APPLICATION_ERROR(-20001,'LA TARJETA DE CRÉDITO NO SE ENCUENTRA VIGENTE.');
  ELSE
    IF EXTRACT(MONTH FROM SYSDATE) > V_MES_EXPIRA AND EXTRACT(YEAR FROM SYSDATE) = V_ANIO_EXPIRA THEN
      RAISE_APPLICATION_ERROR(-20001,'LA TARJETA DE CRÉDITO NO SE ENCUENTRA VIGENTE.');
    END IF;
  END IF;
  SELECT SERVICIO_ID INTO V_EXCENTO FROM SERVICIO_VIAJE WHERE SERVICIO_ID = :NEW.SERVICIO_ID;
  IF :NEW.TIPO_SERVICIO = 'R' AND V_EXCENTO IS NOT NULL THEN
    UPDATE SERVICIO_RENTA SET DIAS_CUSTODIA = TRUNC(:NEW.FECHA_FIN) - TRUNC(:NEW.FECHA_INICIO);
  END IF;
END IF;
END;
/
