-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

CREATE OR REPLACE TRIGGER REEMPLAZAR_SCOOTER
FOR INSERT OR UPDATE ON SCOOTER
COMPOUND TRIGGER
V_SCOOTER_REEMPLAZO NUMBER;
V_PRUEBA NUMBER;
  BEFORE STATEMENT IS
  BEGIN
  SELECT MIN(SCOOTER_ID) INTO V_SCOOTER_REEMPLAZO FROM SCOOTER WHERE STATUS_ID = 2;
  END BEFORE STATEMENT;

  BEFORE EACH ROW IS
  BEGIN 
  IF :NEW.STATUS_ID = 5 THEN
     :NEW.SCOOTER_REEMPLAZO_ID := V_SCOOTER_REEMPLAZO;
  END IF;
  END BEFORE EACH ROW;

  AFTER EACH ROW IS
  BEGIN
  NULL;
  END AFTER EACH ROW;


  AFTER STATEMENT IS
  BEGIN
  NULL;
  END AFTER STATEMENT;

END REEMPLAZAR_SCOOTER;
/