-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

/*  
    Segundo Trigger: Checar la fecha de insersión sea con respecto al caso de estudio.
    Segundo trigger: INICIAR SERVICIO. -> CAMBIAR STATUS DEL SCOOTER, QUITAR MONEY O CRÉDITO.
    TERCER TRIGGER: VERIFICAR QUE LA TARJETA DE CRÉDITO TENGA FONDOS
    CUARTO: ASIGNAR FUERA DE ZONA AL INSERTAR COORDENADAS
    QUINTO: VERIFICAR QUE EL SCOOTER NO SE ENCUENTRA EN OTRO SERVICIO EN CURSO.
*/

PROMPT TRIGGER 2: PARA CHECAR LA DISPONIBILIDAD DE LOS SCOOTERS
PROMPT PARA SERVICIO VIAJE Y RENTA ES NECESARIO QUE SE ENCUENTRE EN STATUS "EN ESPERA"
PROMPT PARA SERVICIO DE RECARGA DEBERÁ ESTAR EN STATUS "APAGADO", "EN ESPERA" O "BATERÍA BAJA"
PROMPT EN CASO QUE NO SE ENCUENTRE DISPONIBLE, SE MANDA UN MENSAJE DE ERROR DE -20002 A -20004

CREATE OR REPLACE TRIGGER DISPONIBILIDAD_SCOOTER_VIAJE
BEFORE INSERT OR UPDATE ON SERVICIO_VIAJE
FOR EACH ROW
DECLARE
  V_STATUS NUMBER:=0;
BEGIN
  SELECT STATUS_ID INTO V_STATUS FROM SCOOTER WHERE SCOOTER_ID = :NEW.SCOOTER_ID;
  IF V_STATUS != 2 THEN
    RAISE_APPLICATION_ERROR(-20102, 'EL SCOOTER NO SE ENCUENTRA DISPONIBLE PARA VIAJE');
  ELSE
    UPDATE SCOOTER SET STATUS_ID = 3 WHERE SCOOTER_ID = :NEW.SCOOTER_ID;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DISPONIBILIDAD_SCOOTER_RENTA
BEFORE INSERT OR UPDATE ON SERVICIO_RENTA
FOR EACH ROW
DECLARE
  V_STATUS NUMBER:=0;
BEGIN
  SELECT STATUS_ID INTO V_STATUS FROM SCOOTER WHERE SCOOTER_ID = :NEW.SCOOTER_ID;
  IF V_STATUS != 2 THEN
    RAISE_APPLICATION_ERROR(-20103, 'EL SCOOTER NO SE ENCUENTRA DISPONIBLE PARA RENTA');
  ELSE
    UPDATE SCOOTER SET STATUS_ID = 6 WHERE SCOOTER_ID = :NEW.SCOOTER_ID;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER DISPONIBILIDAD_SCOOTER_RECARGA
BEFORE INSERT OR UPDATE ON RECARGA_SCOOTER
FOR EACH ROW
DECLARE
  V_STATUS NUMBER:=0;
BEGIN
  SELECT STATUS_ID INTO V_STATUS FROM SCOOTER WHERE SCOOTER_ID = :NEW.SCOOTER_ID;
  IF (V_STATUS = 1) OR (V_STATUS = 2) OR (V_STATUS = 4) THEN
    UPDATE SCOOTER SET STATUS_ID = 7 WHERE SCOOTER_ID = :NEW.SCOOTER_ID;
  ELSE
     RAISE_APPLICATION_ERROR(-20104, 'EL SCOOTER NO SE ENCUENTRA DISPONIBLE PARA REALIZAR RECARGA');
  END IF;
END;
/