-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

SET SERVEROUTPUT ON

DECLARE
BEGIN
  DBMS_OUTPUT('PRUEBA 1: INICIAR SERVICIO A USUARIO CON PUNTOS SUFICIENTES');
  DBMS_OUTPUT('PRUEBA 2: INICIAR SERVICIO A USUARIO SIN PUNTOS PERO TARJETA VIGENTE');
  DBMS_OUTPUT('PRUEBA 3: INICIAR SERVICIO A USUARIO SIN PUNTOS Y TARJETA VENCIDA -> ERROR');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/