CREATE OR REPLACE PROCEDURE INSERT_SERV_VIAJE(

) IS
  E_EXCEPTION_1 EXCEPTION;
  E_ERROR_INMUEBLE EXCEPTION;
  V_CLIENTE_AVAL NUMBER;
BEGIN
    INSERT INTO SERVICIO VALUES();
    INSERT INTO SERVICIO_VAIJE VALUES();
EXCEPTION:

END;
/

CREATE OR REPLACE PROCEDURE INSERT_SERV_RENTA(

) IS
BEGIN
    INSERT INTO SERVICIO VALUES();
    INSERT INTO SERVICIO_VAIJE VALUES();
END;
/


CREATE OR REPLACE PROCEDURE INSERT_SERV_RECARGA(
    
) IS


BEGIN
    INSERT INTO SERVICIO VALUES();
    INSERT INTO SERVICIO_VAIJE VALUES();
END;
/