-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

/*
FUNCIÓN: SE DESEA SABER SI ES FACTIBLE DAR
UNA RECOMPENSA DE 50 PUNTOS A LOS CLIENTES EN EL ÚLTIMO MES POR TENER 
LAS SIGUIENTES CARACTERÍSTICAS. DEPENDIENDO LA QUE MEJOR SALGA PRECIO - OFERTA
SERÁ LA GANADORA, PUEDE CAMBIARSE LA ESTRATEGIA DE MARKETING EL SIGUIENTE MES.
-SE DA COMO OPCIONES LAS SIGUIENTES:
    OPCIÓN 1: 
        - HABER REALIZADO AL MENOS 3 SERVICIOS DE TIPO VIAJE O RENTA O RECARGA.
    OPCIÓN 2:
        - HABER REALIZADO MÁS DE 3 REPORTES DE SCOOTER, 2 VIAJES O RENTAS.
*/

CREATE OR REPLACE FUNCTION FN_CLIENTES_FAVORITOS(OPCION NUMBER, MES NUMBER,ANIO NUMBER) RETURN NUMBER
IS
  PUNTOS_REGALAR NUMBER;
  V_TOTAL NUMBER := 0;
BEGIN
    IF OPCION = 1 THEN
        SELECT COUNT(*) INTO V_TOTAL FROM(
          SELECT U.USUARIO_ID, COUNT(*) FROM USUARIO U, SERVICIO S 
          WHERE U.USUARIO_ID = S.USUARIO_ID
          AND EXTRACT(MONTH FROM S.FECHA_INICIO) = MES
          AND EXTRACT(YEAR FROM S.FECHA_INICIO) = ANIO
          GROUP BY U.USUARIO_ID
          HAVING(COUNT(*) >= 3)
        );
        RETURN V_TOTAL*50;
    ELSIF OPCION = 2 THEN
        SELECT COUNT(*) INTO V_TOTAL FROM(
          SELECT U.USUARIO_ID, COUNT(*)
          FROM USUARIO U, SERVICIO S, (
              SELECT RF.USUARIO_ID, COUNT(*) 
              FROM USUARIO U,
              REPORTE_FALLA RF
              WHERE U.USUARIO_ID=RF.USUARIO_ID
              GROUP BY RF.USUARIO_ID
              HAVING(COUNT(*)>2)
          ) Q1
          WHERE Q1.USUARIO_ID = S.USUARIO_ID
          AND U.USUARIO_ID = S.USUARIO_ID
          AND (S.TIPO_SERVICIO = 'V' OR S.TIPO_SERVICIO = 'R')
          AND EXTRACT(MONTH FROM S.FECHA_INICIO) = MES
          AND EXTRACT(YEAR FROM S.FECHA_INICIO) = ANIO
          GROUP BY U.USUARIO_ID
          HAVING(COUNT(*) >= 2)
        );
        RETURN V_TOTAL*50;
    ELSE
        RETURN -1;
    END IF;
END;