CREATE OR REPLACE FUNCTION FN_FOLIO(PRECIO NUMBER, FECHA DATE,NOMBRE VARCHAR2,
AP_PAT VARCHAR2, AP_MAT VARCHAR2) RETURN VARCHAR2
IS
 V_SALIDA VARCHAR2(13);
BEGIN
  IF PRECIO>300 THEN
    IF EXTRACT(DAY FROM FECHA) > 15 THEN
      SELECT 'SC-'|| TO_CHAR(EXTRACT(YEAR FROM FECHA)-2000) || SUBSTR(NOMBRE,1,1) ||SUBSTR(TO_CHAR(TRUNC(PRECIO)),1,1)||'1312' INTO V_SALIDA FROM DUAL;
    ELSE
      SELECT 'SC-'|| TO_CHAR(EXTRACT(YEAR FROM FECHA)-2000) || SUBSTR(AP_PAT,1,1) ||SUBSTR(TO_CHAR(TRUNC(PRECIO)),1,1)||'4312' INTO V_SALIDA FROM DUAL;
    END IF;
  ELSE
      SELECT 'SC-'|| TO_CHAR(EXTRACT(YEAR FROM FECHA)-2000) || SUBSTR(AP_MAT,1,2) ||SUBSTR(TO_CHAR(TRUNC(PRECIO)),1,2)||'8789' INTO V_SALIDA FROM DUAL;
  END IF;
  RETURN V_SALIDA;
END;
/