-- Companía:  Scooters Anywhere
-- Project:   Modelo Proyecto Final
-- Author:    Garrido Samuel y Jorge Cárdenas
-- Fecha:     04 de Junio del 2020

/*
FUNCIÓN: 
PARA OBTENER EL FOLIO DEL VIAJE SE REALIZA UN 
TIPO COMBINACIÓN NUMÉRICA DADA POR LOS NÚMEROS DENTRO DEL PARÁMETRO.
SI EL PRECIO ES MAYOR A 300
SI ES MÁS DEL 15 DEL MES, TENDREMOS UNA COMBINACIÓN QUE VA CON SU NOMBRE,
EN SEA ANTES DE LA PRIMERA QUINCECA TENDREMOS QUE SERÁ CON SU APELLIDO PATERNO
SI EL MONTO ES MENOR A 300 TENDREMOS UNA COMBINACIÓN CON SU APELLIDO MATERNO.
*/
CREATE OR REPLACE FUNCTION FN_FOLIO(PRECIO NUMBER, FECHA DATE,NOMBRE VARCHAR,
AP_PAT VARCHAR, AP_MAT VARCHAR) RETURN VARCHAR
IS
 V_SALIDA VARCHAR2(13);
BEGIN
  IF PRECIO>300 THEN
    IF EXTRACT(DAY FROM FECHA) > 15 THEN
      SELECT 'SC-'|| TO_CHAR(EXTRACT(YEAR FROM FECHA)) || SUBSTR(NOMBRE,-2,2) ||SUBSTR(TO_CHAR(TRUNC(PRECIO)),1,2)||TO_CHAR(DBMS_RANDOM.Value(10, 99)) INTO V_SALIDA FROM DUAL;
      RETURN  V_SALIDA;
    ELSE
      SELECT 'SC-'|| TO_CHAR(EXTRACT(YEAR FROM FECHA)-2000) || SUBSTR(AP_PAT,-2,2) ||SUBSTR(TO_CHAR(TRUNC(PRECIO)),1,2)||TO_CHAR(DBMS_RANDOM.Value(10, 99)) INTO V_SALIDA FROM DUAL;
      RETURN  V_SALIDA;
    END IF;
  ELSE
      SELECT 'SC-'|| TO_CHAR(EXTRACT(YEAR FROM FECHA)-2000) || SUBSTR(AP_MAT,-2,2) ||SUBSTR(TO_CHAR(TRUNC(PRECIO)),1,1)||TO_CHAR(DBMS_RANDOM.Value(100, 999)) INTO V_SALIDA FROM DUAL;
    RETURN V_SALIDA;
  END IF;
END;
/